### ISSUE TITLE
reporting configuration

### ISSUE THREAD

**Issue by Pierrotws** [adaltas/node-masson#10]
Provide a masson command to generate a 'final' configuration file.
Masson would merge all configuration files, execute *.configure fonctions, then print a report-configuration file.

**Comment by wdavidw** [comment]
+1 would be nice to have

**Comment by lucasbak** [comment]
+1 . Could have a part with the general config and a second part with each's server configured conf

**Comment by wdavidw** [comment]
lucas, from my understanding, what pierre is proposing doesn't change the current mechanism, it only exposes a configure option which print a report. It is like calling any command today (eg "install") but instead of running the install middlewares, it call a masson serializer which convert for each server the "ctx.config" into a suitable output (json by default)

**Comment by lucasbak** [comment]
That's exactly what I meant ! 
I've started a similar work last week which write in a JSON file:
first item - the general config 
other items - each server's ctx.config
So I  agree with the "suitable output" !!
I set the issue as in progress.

**Comment by wdavidw** [comment]
but there are no such thing as a general configuration, only per server

**Comment by lucasbak** [comment]
general configuration as the merge of the configuration file in the /conf/ folder for example, a step before processing the configure function for each server

**Comment by Pierrotws** [comment]
General config report is useless (for my opinion),

if you need the final, per-server configuration, you don't want to merge
manually the general config and the host-specific part...

**Comment by wdavidw** [comment]
as i wrote, there are no such thing as a general configuration. i explain. masson, which functionnality/specs are mostly defined by what's inside "./lib/run and "./lib/tree", doesn't care how configuration is created, it receives a configuration array, one per server, into its constructor ("./lib/run"). It just happens to provide a default configuration provider, "./lib/config", filesystem based and with a notion of a global configuration merged into each server definition. This provider could easily be switched or completed by another one (eg: database, get configuration from the arguments like "-D" in java, ...)

**Comment by lucasbak** [comment]
So let's go for a first draft, with a final output which  would look like the servers.coffee file, but here with all the configure function applied ? To go further, during the process the redundancy and circular references could be removed, to be able to print it as JSON.

**Comment by wdavidw** [comment]
i'll rather wait a bit until someone came with a real need (pierre, maybe u already got one?). the reason is that this ".configure" discovery mechanism is more of a hack today and will have to change in some ways.

**Comment by wdavidw** [comment]
otherwise, if you want to start on it, it shall be inserted [here](https://github.com/adaltas/node-masson/blob/master/lib/run.coffee#L48)

**Comment by lucasbak** [comment]
I agree with you, this place is the step after all configuration are applied, before executing middleware. We can wait a bit to make it more accurate and sharper concerning the needs.
Could we put a report command for it,as the example of lib/commands/run and lib/run put a lib/command/report and lib/report in a separate way, I've seen that a report command already exists but is not yet implemented, is it ?

**Comment by wdavidw** [comment]
report is implemented as a middleware command (eg "install", "status", ...) but not really used. leave it for now, i'll rather call the command "configure"

**Comment by lucasbak** [comment]
+1 for new command configure :)

**Comment by Pierrotws** [comment]
I think we all agree.

Ok so who's gonna work on it ?

**Comment by lucasbak** [comment]
I had already started so I will work on it .If you have other suggestion or requirement tell me.

**Comment by wdavidw** [comment]
Unit test

**Comment by lucasbak** [comment]
fair enough :)

**Comment by Pierrotws** [comment]
Do not postfix with extension
to detect format, in order:
- provider option
- if not, try to detect extension
- if not obvious, default to json
Everybody agrees ?

**Comment by wdavidw** [comment]
look inside the [`write` function inside the capacity script](https://github.com/ryba-io/ryba/blob/master/lib/capacity/index.coffee.md). At the end, the two behaviors shall be aligned.

**Comment by Pierrotws** [comment]
+1

Le jeu. 24 déc. 2015 à 12:43, Worms David <notifications@github.com> a
écrit :
