### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by IDerr** [adaltas/node-masson#16]
## MySQL Server Install : External Root Access

Entering execute (DEBUG, written by nikita/lib/system/execute)

```stdin
function mysql_exec {
  read query
  mysql -hlocalhost -P3306 -uroot -pMySQL123- -N -s -r -e "$query" 2>/dev/null
}
exist=`mysql_exec <<SQL
SELECT count(*) FROM mysql.user WHERE user = 'root' and host = '%';
SQL`
[ $exist -gt 0 ] && exit 3
mysql_exec <<SQL
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'MySQL123-'; UPDATE mysql.user SET Grant_priv='Y', Super_priv='Y' WHERE User='root' and Host='%';
FLUSH PRIVILEGES;
SQL
```

```stderr
bash: line 7: [: -gt: unary operator expected
```

**Comment by IDerr** [comment]
yum info mysql-community-release
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: miroir.univ-paris13.fr
 * epel: nl.mirror.babylon.network
 * extras: ftp.pasteur.fr
 * updates: ftp.ciril.fr
Error: No matching Packages to list

**Comment by wdavidw** [comment]
i can reproduce the error if exist is undefined, which raised the question why is it undefined. probably the query executed before failed. can u had the "trap: true" option to the "@system.execute" run the command ?

**Comment by IDerr** [comment]
In fact, the cmd fails because  mysql-community-release can not be found in the yum repo. I posted the result above.

**Comment by wdavidw** [comment]
yes, you must manually install the "mysql57-community-release-el7" package on centos, i'm waiting for @lucasbak repo module in nikita and some time to add it.

**Comment by lucasbak** [comment]
there is already the nikita.tools.repo action which enables you to download/copy a repo file for yum packet manager. Check https://github.com/adaltas/node-nikita/blob/master/test/tools/repo.coffee to see more examples.

Now if you want an action to install manually a rpm we can discuss with @wdavidw  about this new functionality to follow the api guidelines. opened to suggestions.

**Comment by IDerr** [comment]
Ok, I'll work with that. thanks
