### ISSUE TITLE
Delete JAVA 1.7 and update JAVA 8 

### ISSUE THREAD

**Issue by IDerr** [adaltas/node-masson#26]
Since we can't download the JDK 1.7 anymore : http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

Why don't we delete it from 
https://github.com/adaltas/node-masson/blob/master/commons/java/configure.coffee.md

And update the JDK 1.8 from 1.8.0_101 -> 1.8.0_131

**Comment by IDerr** [comment]
@wdavidw

**Comment by wdavidw** [comment]
I have discussed with @lucasbak a few weeks back while speaking about the repositories and password current usage. The goal is to have more generic services and parameters which are client specifics (such as a repo url, a password or the url to java) should be handled by the user from the configuration. In the java service exemple, we should not define the url in the service configuration with in the user env configuration, and provide a nice exemple in the service configuration. At least that was the idea and I'm open to discuss everyone point of view on the subject.

**Comment by IDerr** [comment]
I am ok with that, but in the default masson configure, we should keep only the java 1.8 no ?
Or do you mean, that we have to delete all the default java config in masson and put them on the config.json  ?

**Comment by wdavidw** [comment]
The discussion is around removing all, not saying we shall do it or not, i'm hesitating
