### ISSUE TITLE
package: migration script

### ISSUE THREAD

**Issue by wdavidw** [adaltas/node-masson#31]
On the road to the next version which will refactor how service are described and configured, we will put in place a migration module which act as a wrapper at the beginning of any "configure" functions. This way, we could test and migrate to the new API witout having to re-write all the service at once and without having to touch at the "run" module before anything else is ready.

Here's how to call the "migration" function: 

```js
module.exports = (service) ->
  service = migration service, 'path/to/module', ['config', 'key'], require('nikita/lib/misc').merge require('.').use,
    'dependency', ['config', 'dependency', 'key']
  console.log service.options
  console.log service.node
  console.log serrvice.use.dependency.options
  console.log serrvice.use.dependency.node
```

**Comment by wdavidw** [comment]
Can we close this, this seems pretty stable on my side, meaning we can merge to master

**Comment by IDerr** [comment]
I'll try an install tomorrow to try on a fresh install

**Comment by IDerr** [comment]
I think we can close this issue @wdavidw ?
