### ISSUE TITLE
Epel version

### ISSUE THREAD

**Issue by IDerr** [adaltas/node-masson#32]
Hi, is there a reason why are we using epel from centos 6 and not centos 7 ?

core/yum/configure.coffee.md:
Instead of  
http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
we could use 
http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm

Thanks

**Comment by wdavidw** [comment]
Personnaly, I dont have epel activated and even when it was, I was referencing an offline repo on epe 7. This should be removed from the configuration file. 2 options:
* remove it enterely and throw an error if epel is activated and the url not provided by the user
* move it to install and use nikita os detection if url is not provided by the user (my preference)

**Comment by wdavidw** [comment]
Summer cleanup :)
